### ISSUE TITLE
Resizing .ico files

### ISSUE THREAD

**Issue by elevatednetwork** [chrisbliss18/php-ico#2]
I wanted to use this class to convert larger 48x48px .ico files to smaller 16x16px .ico files and it seems to be throwing errors for me.

**Comment by chrisbliss18** [comment]
As noted in the description, the GD library is used for reading in image data. Unfortunately, the GD library does not support reading in ICO files, and it's well beyond the scope of this project to write a library for converting ICO image data to a GD image format. Thus, you will be unable to use php-ico for what you want.
