### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by marieneig** [chrisbliss18/php-ico#3]
Hi I think some files are missing right? there is no form and the page is blank. So you provide the php and we make the rest, right? thank you

**Comment by chrisbliss18** [comment]
php-ico is a code library that can be used to build other projects. In other words, php-ico doesn't do anything on its own and requires other code to make it do something.

If you are looking for a ready-built site that allows for submission of images to convert into ICO files, you will have to find the solution elsewhere.

**Comment by marieneig** [comment]
Ok thank you, it is good I will keep it for later
